In [ ]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [7]:
df=pd.read_csv("tel_churn.csv")

In [8]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29,29,0,1,0,0,1,1,...,0,0,1,0,1,0,0,0,0,0
1,1,0,56,1889,0,0,1,1,0,1,...,0,0,0,1,0,0,1,0,0,0
2,2,0,53,108,1,0,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0
3,3,0,42,1840,0,0,1,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,4,0,70,151,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0

In [10]:
df=df.drop('Unnamed: 0',axis=1)

In [11]:
df

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29,29,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,0,0
1,0,56,1889,0,0,1,1,0,1,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53,108,1,0,1,1,0,1,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42,1840,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0
4,0,70,151,1,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84,1990,0,0,1,0,1,0,1,...,0,0,0,1,0,1,0,0,0,0
7028,0,103,7362,0,1,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
7029,0,29,346,0,1,0,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0
7030,1,74,306,1,0,1,0,1,1,0,...,0,0,0,1,1,0,0,0,0,0
7031,0,105,6844,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,0,0,1

In [12]:
x=df.drop('Churn',axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29,29,1,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,0
1,0,56,1889,0,1,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53,108,0,1,1,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42,1840,0,1,1,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,0,70,151,1,0,1,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84,1990,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
7028,0,103,7362,1,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,1
7029,0,29,346,1,0,0,1,0,1,1,...,0,0,1,0,1,0,0,0,0,0
7030,1,74,306,0,1,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
7031,0,105,6844,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1

In [13]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

Decision tree

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [20]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [21]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [22]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 1, 1], shape=(1407,), dtype=int64)

In [23]:
model_dt.score(x_test,y_test)

0.7782515991471215

In [24]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1003
           1       0.64      0.52      0.57       404

    accuracy                           0.78      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.77      0.78      0.77      1407

As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datasets.
Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.
Hence, moving ahead to call SMOTEENN (UpSampling + ENN)

In [28]:
%pip install imbalanced-learn

In [31]:
from imblearn.combine import SMOTEENN
from sklearn.model_selection import train_test_split

In [32]:
sm = SMOTEENN()

X_resampled, y_resampled = sm.fit_resample(x, y)

In [33]:
xr_train, xr_test, yr_train, yr_test = train_test_split(
    X_resampled,
    y_resampled,
    test_size=0.2,
    random_state=42
)

In [34]:
print(X_resampled.shape)
print(y_resampled.shape)

(5824, 50)
(5824,)

In [35]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [36]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9064377682403434
              precision    recall  f1-score   support

           0       0.93      0.87      0.90       553
           1       0.89      0.94      0.91       612

    accuracy                           0.91      1165
   macro avg       0.91      0.90      0.91      1165
weighted avg       0.91      0.91      0.91      1165

In [37]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[483  70]
 [ 39 573]]

Now we can see quite better results, i.e. Accuracy: 91 %, and a very good recall, precision & f1 score for minority class.
Let's try with some other classifier.

### Random forest classfier

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [40]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [42]:
y_pred=model_rf.predict(x_test)

In [43]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.80      0.92      0.85      1003
           1       0.68      0.42      0.52       404

    accuracy                           0.78      1407
   macro avg       0.74      0.67      0.69      1407
weighted avg       0.76      0.78      0.76      1407

In [45]:
sm = SMOTEENN()

X_resampled1, y_resampled1 = sm.fit_resample(x, y)

In [46]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [47]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [48]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [49]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [50]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [51]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9247863247863248
              precision    recall  f1-score   support

           0       0.95      0.88      0.92       538
           1       0.90      0.96      0.93       632

    accuracy                           0.92      1170
   macro avg       0.93      0.92      0.92      1170
weighted avg       0.93      0.92      0.92      1170

In [52]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[474  64]
 [ 24 608]]

In [53]:
import pickle

In [54]:
filename = 'model.sav'

In [55]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [56]:
load_model = pickle.load(open(filename, 'rb'))

In [57]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [58]:
model_score_r1

0.9247863247863248